### ISSUE TITLE
Class Bbsnly\\ChartJs\\ChartServiceProvider removed but used in composer.json as laravel provider

### ISSUE THREAD

**Issue by TomSchenk** [bbsnly/chartjs-php#5]
* PHP: v7.4.16

### Description

Version 3.x ist currently not installable with laravel package discovery

### Steps To Reproduce

* `composer require bbsnly/chartjs-php:3.0.0`
* `php artisan package:discover`

**Comment by 831220** [comment]
Also waiting for this. I had to install version 2.1.1 meanwhile.
Any other idea or alternative you know until developer fix it?

**Comment by bbsnly** [comment]
Please open a PR and I'll merge it
